### ISSUE TITLE
だおんで勤怠管理する

### ISSUE THREAD

**Issue by yutokyokutyo** [yutokyokutyo/yutokyokutyo#6]
https://github.com/yutokyokutyo/kinnosuke-clocking-cli

**Comment by achamixx** [comment]
これは最高

**Comment by hfm** [comment]
👀

**Comment by yano3** [comment]
👀

**Comment by yutokyokutyo** [comment]
👀 ❗️ ❗️ ❗️

**Comment by yutokyokutyo** [comment]
## 概要
人間は不思議な生き物で、絶対に来なければいけない時間が10時から12時に変更になり2時間も延長されたのにも関わらず、なぜか12時ギリギリに出社するという場面が起きてしまう。
そんな1分1秒を争う場面で、わざわざPCを保管ボックスから出してPCを立ち上げブラウザを開きボタンを押すという作業は致命的。
そんな非常事態のために、ボタンをポチッと押せば一瞬で出勤できる君を作る。
机においておくことになるので、無機質なマシーンよりも愛着が湧く見かけの方が幸せになる。
つまりその子にだおんを被せる。

**Comment by yutokyokutyo** [comment]
東工大の授業でラズパイをたくさん使ったのですが、その残骸が手元に溢れいてるので、この子達を活かしてあげるという意味を含めてラズパイを使います。

まずはラズパイにgoをinstallする。

```go
$ sudo apt-get install -y gcc libc6-dev mercurial
$ cd /usr/local
$ sudo hg clone -u default https://code.google.com/p/go
$ cd go/src
$ sudo ./make.bash
---以下~/.bashrcに追記---
$ export GOROOT=/usr/local/go
$ export GOPATH=$HOME/repos/gohome
$ export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

**Comment by yutokyokutyo** [comment]
この辺を参考にしていきます。
https://medium.com/eureka-engineering/go%E5%88%9D%E5%BF%83%E8%80%85%E3%81%A7%E3%82%82%E3%81%99%E3%81%90%E3%81%A7%E3%81%8D%E3%82%8B-raspberry-pi%E3%81%A8%E7%B5%84%E3%81%BF%E5%90%88%E3%82%8F%E3%81%9B%E3%81%A6%E7%B4%A0%E6%97%A9%E3%81%8F%E7%9B%AE%E8%A6%9A%E3%81%BE%E3%81%97%E3%82%92%E4%BD%9C%E3%82%8B%E6%96%B9%E6%B3%95-84fb5a535508

**Comment by yutokyokutyo** [comment]
スイッチ用の回路でけた。
![img_0672](https://user-images.githubusercontent.com/7356977/38370671-9e29b17a-3925-11e8-9573-6fad1d8e1eff.JPG)

**Comment by yutokyokutyo** [comment]
ラズパイゼロも余っているのでラズパイ3で動作確認取れたらラズパイゼロにデータを全部移行しよう。
そのほうが軽いし小さくてスマート。

**Comment by yutokyokutyo** [comment]
http://dotnsf.blog.jp/archives/1066911287.html

**Comment by yutokyokutyo** [comment]
apt-get install でいくつか失敗していたので `sudo apt-get update`  した。

**Comment by yutokyokutyo** [comment]
正常にinstallできた模様。

**Comment by yutokyokutyo** [comment]
> MercurialはPythonで実装されたクロスプラットフォームのソースコード管理システムです。コマンドラインのフロントエンドの名称である「hg」という名前でも呼ばれています。

**Comment by yutokyokutyo** [comment]
う〜ん。。
`sudo hg clone -u default https://code.google.com/p/go` でclone に失敗するなぁ。

```
pi@raspberrypi:/usr/local $ sudo hg clone -u default https://code.google.com/p/go
Traceback (most recent call last):
  File "/usr/bin/hg", line 43, in <module>
    mercurial.dispatch.run()
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 69, in dispatch
    ret = _runcatch(req)
  File "/usr/lib/python2.7/dist-packages/mercurial/dispatch.py", line 227, in _runcatch
    ui.warn(_("abort: error: %s\n") % reason)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

**Comment by yutokyokutyo** [comment]
ちょっとhg clone に馴染みがなさすぎるので、愚直にwgetする作戦に変更。

**Comment by yutokyokutyo** [comment]
```
$ wget https://storage.googleapis.com/golang/go1.8.linux-armv6l.tar.gz
$ sudo tar -C /usr/local -xzf go1.8.linux-armv6l.tar.gz
```

環境変数設定して go を install 出来たことを確認

```
pi@raspberrypi:/tmp $ go version
go version go1.8 linux/arm
```

**Comment by yutokyokutyo** [comment]
GOPATHを設定したディレクトリにhttps://github.com/yutokyokutyo/kinnosuke-clocking-cli を git clone した。

**Comment by yutokyokutyo** [comment]
go get -u github.com/yano3/kinnosuke-clocking-cli も成功したぽい

**Comment by yutokyokutyo** [comment]
```
pi@raspberrypi:~/go/kinnosuke-clocking-cli $ export -p | grep 'KINNOSUKE_'
declare -x KINNOSUKE_COMPANYCD="ほげほげ"
declare -x KINNOSUKE_LOGINCD="ほげほげ"
declare -x KINNOSUKE_PASSWORD="ほげほげ"
```
を確認。

**Comment by yutokyokutyo** [comment]
準備はできた！
後はボタンを押したら `kinnosuke-clocking-cli` が走ればOK！

#### 備忘録
- 成功したら音がピッとなるという仕様にするとよりよいかも
- 自分以外の人が使えるようにするためには....
    - Webサービスと連動する個人を特定する何かを作って、お客様ID,ログインID,パスワード, 個人を特定する何か(顔, 指紋, Felica?)をまずは登録してもらう
    - だおんに個人を特定する何かによって個人を特定
    - 認証OK!としたら出勤。退勤とか？
- 会話して出勤、退勤は他人がいる中で声を出す必要があるから使ってもらえなさそう。ナンセンス。

**Comment by yutokyokutyo** [comment]
https://github.com/hybridgroup/gobot 
Go言語製ロボティクスフレームワークのGobotを使ってGPIO制御

**Comment by yutokyokutyo** [comment]
go get github.com/hybridgroup/gobot

**Comment by yutokyokutyo** [comment]
ラズパイ、Arduinoはもちろん、腕時計のPebbleやドローンなど、32のプラットフォームに対応

**Comment by yutokyokutyo** [comment]
GPIOの設定をONにする。
VNC Viewer を使えるようにしておく。

**Comment by yutokyokutyo** [comment]
GPIOはnodeを使って制御しよう。

`npm install onoff`

**Comment by yutokyokutyo** [comment]
押すと反応する！おｋ！

```
pi@raspberrypi:~/kinnosuke-button $ node poti.js
Button has been pressed
Button has been pressed
Button has been pressed
Button has been pressed
Button has been pressed
```

**Comment by yutokyokutyo** [comment]
明日出勤したらテストしてみる。今日は終わり。

**Comment by yutokyokutyo** [comment]
https://github.com/yutokyokutyo/kinnosuke-button

**Comment by yutokyokutyo** [comment]
成功したら「だおん！」って小さく音がなる仕様にしよう。

**Comment by yutokyokutyo** [comment]
社内のタブレット用無線LANがラズパイからは認識できなかった 😢 
無線に繋がらないと打刻できないので詰んだ。誰かに相談しよう。

**Comment by yutokyokutyo** [comment]
現状セキュリティ上の問題で実現できないことが分かった。ので、日を改めよう。
入社時に思っていた `作りたい！と思ったものをすぐに作れるようになれるようになる` ができた例だったので楽しくって嬉しかった！
また違うものを作ろ〜！

**Comment by yutokyokutyo** [comment]
どうやら出勤漏れが多くなっている模様。
自分のPCカメラで顔認識して、PCが「あ！この人はAさんだ！」と認識したら `出勤` とする。とかよさそう。
その日朝7:00以降に初めて顔認識したら `出勤` 
いや、自分のPCだったら顔認識する必要はないのか。

出勤漏れはどっちなんだろう。退勤かな。
退勤はどうするとよいのかな。

やっぱりボタンかなぁ。PCを介せば問題ないからボタンをPCに取り付けられるタイプの何かとか？

**Comment by Fendo181** [comment]
👀 !!!
